cache:
  paths:
    - node_modules/

# variables:
#   VARIABLES_FILE: ./variables.txt

build:
  stage: build
  image: node:latest
  script:
    - mkdir artifacts
    - npm install
    - set NODE_ENV=default
    - node index.js # Build Source Code in Output Directory
    - cp -R ./output/** artifacts
    - ls ./artifacts
  # only:
  #   - /[\w]*+.([0-9])+.([0-9])+.([0-9])+/
  tags:
    - docker

deploy:
  image: node:latest
  stage: .post
  needs: ["build"]
  script:
    - npm install
    - node github_deploy.js
    # - node gitlab_deploy.js
  # only:
  #   - /[\w]*+.([0-9])+.([0-9])+.([0-9])+/
  tags:
    - docker
  # after_script:
  #   - node success_upload.js

stages:
  - build