cache:
  paths:
    - node_modules/

# variables:
#   VARIABLES_FILE: ./variables.txt

build:
  stage: build
  image: node:latest
  script:
    - mkdir artifacts
    - npm install
    - set NODE_ENV=default
    - node index.js # Build Source Code in Output Directory
    - cp -R ./output/** artifacts
    - ls ./artifacts/javascript
  artifacts:
    paths:
      - artifacts
    expire_in: 30 days
  tags:
    - docker

deploy:
  image: node:latest
  stage: .post
  needs: ["build"]
  script:
    - node github_deploy.js
  artifacts:
    paths:
      - artifacts
    expire_in: 30 days
  tags:
    - docker

stages:
  - build